services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - TZ=${TZ}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PUBLIC_URL}
    volumes:
      - ${JELLYFIN_CONFIG}:/config
      - ${MEDIA_ROOT}/shows:/data/tvshows
      - ${MEDIA_ROOT}/movies:/data/movies
      - ${MEDIA_ROOT}/music:/data/music
    ports:
      - "8096:8096"
    networks:
      - jellyfin_default
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  jellyfin_default:
    name: jellyfin_default
    driver: bridge
